### ISSUE TITLE
[Bug Report] Title

### ISSUE THREAD

**Issue by IdrissGarfa** [alovajs/alova#39]
### Reproduction Link

https://github.com/IdrissGarfa/react-alova

### alova Version

v2.0.16

### Describe the Bug

I'm trying to test alova with react js 18.2 using vite 4.2. whenever i made a get request to a local api [localhost:3000/quotes] I get a response with [type: cors] without data! I have done many searches about cors in client side but i didn't get any solutions
![alova](https://user-images.githubusercontent.com/68515775/230756981-05c44bb4-dbf9-4dc4-af32-d52f27fed4c3.png)

### Reproduce Steps

![alova](https://user-images.githubusercontent.com/68515775/230756981-05c44bb4-dbf9-4dc4-af32-d52f27fed4c3.png)

### Device / Browser / Browser Version

Google Chrome

**Comment by JOU-amjs** [comment]
👋🏻Hey, IdrissGarfa! Thanks for your issue, and thanks for loving alova.
I found the problem of your demo.

In the demo, server side run on `http://localhost:3000` and client side run on `http://localhost:5173`, which needs to CORS(the port is different~~~), and your error is not here.

your really error is... emmmm.... it's a spelling error, see below

```js
const alovaInstance = createAlova({
    // ...
    
    // Use two items of the array to specify the interceptor for successful request and the interceptor for failed request
    - responded: {
    + responsed: {
      // ...
    }
});
```

you need change `responded` to `responsed`.... about the word `responsed`, it was my mistake which have a incorrect spelling. I will correct it and make it compatible in the next minor version.

In addition, I notice it return the `json.data` in `onSuccess`, see below.
```js
// ...
    onSuccess: async (response, method) => {
      if (response.status >= 400) {
        throw new Error(response.statusText);
      }
      const json = await response.json();
      if (json.code !== 200) {
        throw new Error(json.message);
      }
      // 👇🏻Here
      return json.data;
    },
```

but the api `http://localhost:3000/quotes` is always return a array, so that you never get the right data.
<img width="617" alt="image" src="https://user-images.githubusercontent.com/29848971/230762922-92ac536c-28e6-45f1-a6da-f16f9fcb834c.png">

so you should correct the response data, such as this.
```js
app.get('/quotes', (req, res) => {
    res.json({
        code: 200,
        data: quotes
    });
})
```

**Comment by IdrissGarfa** [comment]
Hi 👋, Thanks for responding and thank you for developing such an amazing tool! 
Issue resolved and fixed!
