### ISSUE TITLE
[Bug Report] ntime-core.esm-bundler.js:40 [Vue warn]: onUnmounted is called when there is no active component instance to be associated with.

### ISSUE THREAD

**Issue by rifaideen** [alovajs/alova#60]
### Reproduction Link

-

### alova Version

2.1.2

### Describe the Bug

Whenever I navigate between pages, I get this error.

Unmounted is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup(). If you are using async setup(), make sure to register lifecycle hooks before the first await statement. 
 
Looks like the problem is here:

effectRequest({ handler, removeStates, immediate, watchingStates }) {
        // 组件卸载时移除对应状态
        onUnmounted(removeStates);
        immediate && handler();
        let timer;
        forEach(watchingStates || [], (state, i) => {
            watch(state, () => {
                timer && clearTimeoutTimer(timer);
                timer = setTimeoutFn(() => {
                    handler(i);
                    timer = undefinedValue;
                });
            }, { deep: trueValue });
        });
    }

### Reproduce Steps

Install the library and use it in pinia store to perform the network operations and observe the error.

Note: Alova library is not imported in the component level. It is being used by pinia stores.

**Comment by JOU-amjs** [comment]
Hi,rifaideen! 
Thanks for your issue, I read your issue, and I can image your code.

emm.... I guess you were using `useRequest` in pinia store which is not recommend to do, the use hook should use in component, that would be make sense.

If you want to send request outside component, you can use a method instance, such as `alovaInst.Get('...').send()` instead of `useRequest`.

for detail: https://alova.js.org/next-step/send-request-directly

**Comment by maicFir** [comment]
To install them, you can run: npm install --save alova/GlobalFetch alova/vue

**Comment by JOU-amjs** [comment]
@maicFir you can report the bug in this issue, and you can show your reproduction link that I can reproduct problem quickly
