### ISSUE TITLE
[Bug Report] useFetcher cause cache data error

### ISSUE THREAD

**Issue by EasonLin0716** [alovajs/alova#62]
### Reproduction Link

https://codesandbox.io/s/suspicious-rosalind-er2b82?file=/src/App.vue

### alova Version

^2.1.2

### Describe the Bug

Hi, I have a bug to report.

This example was copied from official Doc here:  

https://alova.js.org/zh-CN/tutorial/learning/use-fetcher#%E9%A2%84%E5%8A%A0%E8%BD%BD%E6%95%B0%E6%8D%AE

Problem seems to be here:

```
onSuccess(() => {
  fetch(getTodoList(currentPage.value + 1));
});
```

It would cause alova.js to bring wrong data after page data is cached.

### Reproduce Steps

1. Click 3 pages to let alova.js cache the data.
2. Click page 3
3. Click page 2, nothing would happen.
4. Click page 1, page 2 data will be shown.

### Device / Browser / Browser Version

Chrome 112.0.5615.138

**Comment by JOU-amjs** [comment]
I am sorry for late!!!
I tried your demo and reproduce the problem, emm.... until now, I not sure that it is bug, because the hook `useFetcher` is designed to update states if it exists. I've been thinking about it for a long time but have no idea how to resolve it now.

If you want to use hook in pagination such as a data list or a data table, you can use [usePagination](https://alova.js.org/strategy/usePagination) which also support prefetch next page data and previous page data.

And if I have a idea to resolve it (fix or redesign it), I would post it here as soon as possible.

**Comment by JOU-amjs** [comment]
This difficult childbirth problem has finally been solved.
